# T2E4: Solving Linear Programs with CVXPY

## Basics

First, import the necessary packages `numpy` (for vector mathematics) and `cvxpy` (for optimization).

In [1]:
import numpy as np
import cvxpy as cp

Now define the decision variable $x=[x_1, x_2, x_3]^\top$. This can be done with `cp.Variable(shape)`. <br>Use shape $(rows, columns)=(3,1)$ to model the 3 decision variables.

In [2]:
x = cp.Variable((3,1))

Next, define an array containing all the constraints (use `>=` for *greater-equal*, `<=` for *less-equal* and `==` for *equal*). You can use these inequalities directly on vectors. <br>Hint: Define `c_i` vectors for constraint i and write the constraints using them. Define a numpy array with `np.array(elements)`.
Use `.T` to denote the transpose and `@` for matrix multiplication.

In [3]:
c1 = np.array([[1],[-1],[1]])
c2 = np.array([[3],[2],[4]])
c3 = np.array([[3],[2],[0]])

constraints = [
    x>=0, # all x greater or equal to 0
    c1.T@x<=20, # constraints written in matrix form
    c2.T@x<=42,
    c3.T@x<=30
]

Define the objective: We want to minimize (`cp.Minimize`) $o^\top x$ for $o = [-5, -4, -6]^\top$

In [4]:
o = np.array([[-5],[-4],[-6]]) # define o
objective = cp.Minimize(o.T@x) # define the objective

We are now ready to solve the problem. For this, first combine the objective and constraints to formulate the problem using `cp.Problem`. You can then use `.solve()` on the problem to solve the problem.

In [5]:
problem = cp.Problem(objective, constraints) # define the problem
problem.solve() # solve it

-77.99999997665509

This directly outputs the optimal objective value. It is $-78$ (note the small error due to numerical errors). <br>
Let's now examine the optimal values of x using `.value` on x.

In [6]:
x.value

array([[6.38279109e-10],
       [1.50000000e+01],
       [3.00000000e+00]])

Check out the [CVXPY Website](https://www.cvxpy.org/index.html) for more information and examples.

## Advanced Topics (Optional)

We will now show some thing that will be useful later in the course. Don't worry, you don't have to understand this now, just come back to it once we cover this in the course.

### Dual Variables
You can use `.dual_value` on any constraint to get the value of the dual variable of the optimal solution. Note that you can index python lists using `list[i]` to get the ith element in the list.

In [7]:
constraints[1].dual_value

array([[6.17979799e-11]])

### Solver choice
We will now specify using a specific solver (OSQP) by using `solver=cp.OSQP` as an optional arugment when solving the problem.

In [8]:
problem.solve(solver=cp.OSQP)

-78.0

In [9]:
x.value

array([[1.30643833e-22],
       [1.50000000e+01],
       [3.00000000e+00]])

You can consult the list of solvers on the [CVXPY website](https://www.cvxpy.org/tutorial/advanced/index.html#choosing-a-solver)

### Binary variables
We will now solve a simple example problem using binary variables (which take value either 1 or 0). This is done by using `boolean=True` when defining the variable.

In [10]:
x = cp.Variable((3,1), boolean=True)

In [11]:
# find the largest element in a vector
o = np.array([[2],[3],[5]])
objective = cp.Minimize(-o.T@x)

ones = np.array([[1],[1],[1]])
constraints = [ones.T@x<=1]

problem = cp.Problem(objective, constraints)
problem.solve()

-5.0

In [12]:
x.value

array([[0.],
       [0.],
       [1.]])

The third element is indeed the largest (5)

(In the same way you can use `integer=True` to specify integer values)